<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { club, disciplines, story } from './content/club'
import ThreeCourt from './components/ThreeCourt.vue'

const activeScene = ref(0)
const scrollY = ref(0)
const sceneProgress = computed(() => Math.min(Math.max(scrollY.value / 820, 0), 1))
const shieldStyle = computed(() => ({
  transform: `translate3d(0, ${sceneProgress.value * -42}px, 0) rotate(${sceneProgress.value * 7 - 3.5}deg)`,
}))

function updateScroll() {
  scrollY.value = window.scrollY
  const storyTop = document.querySelector('#historia')?.offsetTop ?? 0
  const relativeScroll = Math.max(window.scrollY - storyTop, 0)
  activeScene.value = Math.min(Math.floor(relativeScroll / 420), story.length - 1)
}

function scrollToSection(id) {
  document.querySelector(id)?.scrollIntoView({ behavior: 'smooth' })
}

onMounted(() => {
  updateScroll()
  window.addEventListener('scroll', updateScroll, { passive: true })
})

onBeforeUnmount(() => window.removeEventListener('scroll', updateScroll))
</script>

<template>
  <div class="site-shell">
    <div class="grain" aria-hidden="true"></div>
    <header class="site-header">
      <a class="brand" href="#inicio" aria-label="Francisco’s Club, volver al inicio">
        <span class="brand-mark"><img src="/escudo-franciscos-club.png" alt="" /></span>
        <span class="brand-copy"><strong>FRANCISCO’S</strong><small>CLUB</small></span>
      </a>
      <nav class="main-nav" aria-label="Navegación principal">
        <a href="#club">El club</a><a href="#experiencia">Experiencia</a><a href="#visitanos">Visítanos</a>
      </nav>
      <button class="header-action" type="button" @click="scrollToSection('#visitanos')">Ven a conocernos <span aria-hidden="true">↗</span></button>
    </header>

    <main>
      <section id="inicio" class="hero" aria-labelledby="hero-title">
        <div class="hero-ambient ambient-left" aria-hidden="true"></div><div class="hero-ambient ambient-right" aria-hidden="true"></div>
        <div class="hero-content">
          <p class="eyebrow"><span class="live-dot"></span> Paucarpata · Arequipa · Perú</p>
          <h1 id="hero-title">Juega.<br /><em>Comparte.</em><br />Pertenece.</h1>
          <p class="hero-intro">{{ club.intro }}</p>
          <div class="hero-actions"><button class="button button-primary" type="button" @click="scrollToSection('#experiencia')">Descubre el club <span aria-hidden="true">↓</span></button><a class="text-link" href="#visitanos">Encuentra tu camino <span aria-hidden="true">↗</span></a></div>
        </div>
        <div class="hero-emblem" aria-hidden="true">
          <div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><img :style="shieldStyle" src="/escudo-franciscos-club.png" alt="" /><span class="emblem-caption">F · C <span></span> 2019</span>
        </div>
        <div class="hero-bottom"><span>Scroll para explorar</span><span class="scroll-line"></span><span>01—03</span></div>
      </section>

      <section id="historia" class="story-section" aria-labelledby="story-title">
        <div class="story-stage">
          <div class="stage-copy"><p class="eyebrow light">La historia del club</p><div class="story-slides"><article v-for="(scene, index) in story" :key="scene.kicker" class="story-slide" :class="{ active: activeScene === index }"><p class="scene-kicker">{{ scene.kicker }}</p><h2 :id="index === 0 ? 'story-title' : undefined">{{ scene.title }}</h2><p>{{ scene.text }}</p></article></div></div>
          <div class="story-graphic"><ThreeCourt /></div>
          <div class="story-progress" aria-hidden="true"><span v-for="(_, index) in story" :key="index" :class="{ active: activeScene === index }"></span></div>
        </div><div class="story-spacer" aria-hidden="true"></div>
      </section>

      <section id="experiencia" class="experience-section section-padding" aria-labelledby="experience-title">
        <div class="section-heading"><p class="eyebrow">Más que deporte</p><h2 id="experience-title">Un lugar para<br /><em>quedarte.</em></h2><p class="section-lead">La experiencia Francisco’s Club se vive en movimiento, en la mesa y en la gente que vuelve.</p></div>
        <div class="discipline-grid">
          <article v-for="item in disciplines" :key="item.number" class="discipline-card"><div class="card-top"><span>{{ item.number }}</span><span class="card-tag">{{ item.tag }}</span></div><div class="card-icon" aria-hidden="true">
            <svg v-if="item.number === '01'" viewBox="0 0 80 80" fill="none"><circle cx="40" cy="40" r="26" stroke="currentColor" stroke-width="1.5"/><path d="M14 40h52M40 14c8 7 12 16 12 26s-4 19-12 26M40 14c-8 7-12 16-12 26s4 19 12 26" stroke="currentColor" stroke-width="1.5"/><path d="m35 38 5-3 5 3v6l-5 3-5-3v-6Z" fill="currentColor"/></svg>
            <svg v-else-if="item.number === '02'" viewBox="0 0 80 80" fill="none"><path d="M20 25h40M24 25v31h32V25M29 19v8M40 19v8M51 19v8M18 56h44M31 39h18" stroke="currentColor" stroke-width="1.5"/><path d="M34 46h12" stroke="currentColor" stroke-width="3"/></svg>
            <svg v-else viewBox="0 0 80 80" fill="none"><circle cx="40" cy="28" r="9" stroke="currentColor" stroke-width="1.5"/><circle cx="23" cy="39" r="7" stroke="currentColor" stroke-width="1.5"/><circle cx="57" cy="39" r="7" stroke="currentColor" stroke-width="1.5"/><path d="M25 62c1-10 7-16 15-16s14 6 15 16M10 62c1-8 5-12 12-12 4 0 7 2 9 5M70 62c-1-8-5-12-12-12-4 0-7 2-9 5" stroke="currentColor" stroke-width="1.5"/></svg>
          </div><h3>{{ item.title }}</h3><p>{{ item.text }}</p><a href="#visitanos" class="card-link">Conoce más <span aria-hidden="true">↗</span></a></article>
        </div>
      </section>

      <section id="club" class="club-section section-padding" aria-labelledby="club-title">
        <div class="club-image-panel"><div class="image-panel-label"><span>01</span><span>Identidad</span></div><img src="/escudo-franciscos-club.png" alt="Escudo dorado de Francisco’s Club" /><div class="image-panel-note">Nuestro escudo,<br /><em>nuestro punto de encuentro.</em></div></div>
        <div class="club-copy-panel"><p class="eyebrow">La casa de Francisco’s Club</p><h2 id="club-title">Tu próxima<br /><em>buena historia.</em></h2><p class="club-description">{{ club.claim }} {{ club.intro }}</p><div class="fact-list"><div><span>Inicio de actividades</span><strong>{{ club.founded }}</strong></div><div><span>RUC</span><strong>{{ club.ruc }}</strong></div><div><span>Condición</span><strong class="status"><i></i>{{ club.status }}</strong></div></div><button class="button button-dark" type="button" @click="scrollToSection('#visitanos')">Planifica tu visita <span aria-hidden="true">↗</span></button></div>
      </section>

      <section id="visitanos" class="visit-section section-padding" aria-labelledby="visit-title"><div class="visit-intro"><p class="eyebrow">Te estamos esperando</p><h2 id="visit-title">Nos vemos<br /><em>en la cancha.</em></h2></div><div class="visit-details"><div class="detail-block"><span class="detail-label">Dirección legal</span><p>{{ club.address }}<br />{{ club.addressDetail }}</p></div><div class="detail-block"><span class="detail-label">Lo que encuentras</span><p>{{ club.activities[0] }}<br />{{ club.activities[1] }}</p></div><a class="button button-primary visit-button" href="https://www.google.com/maps/search/?api=1&query=Paucarpata%20Arequipa" target="_blank" rel="noopener">Abrir en Maps <span aria-hidden="true">↗</span></a></div></section>
    </main>

    <footer class="site-footer"><a class="brand footer-brand" href="#inicio"><span class="brand-mark"><img src="/escudo-franciscos-club.png" alt="" /></span><span class="brand-copy"><strong>FRANCISCO’S</strong><small>CLUB</small></span></a><p>{{ club.legalName }} · Arequipa, Perú</p><a href="#inicio" class="back-top">Volver arriba ↑</a></footer>
  </div>
</template>

<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&family=Playfair+Display:ital,wght@0,600;1,600;1,700&display=swap');
:root { --ink: #101112; --cream: #f3efe5; --paper: #faf8f2; --gold: #c99a3b; --gold-light: #e7c06a; --muted: #827d70; --line: rgba(16,17,18,.14); }
* { box-sizing: border-box; } html { scroll-behavior: smooth; } body { margin: 0; min-width: 320px; background: var(--cream); color: var(--ink); font-family: 'Manrope', sans-serif; } button, a { font: inherit; } button { cursor: pointer; } a { color: inherit; text-decoration: none; }
.site-shell { overflow-x: clip; position: relative; } .grain { pointer-events: none; position: fixed; inset: 0; opacity: .05; z-index: 10; background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.55'/%3E%3C/svg%3E"); }
.site-header { align-items: center; display: flex; height: 88px; justify-content: space-between; left: 0; padding: 0 5vw; position: absolute; right: 0; top: 0; z-index: 4; } .brand { align-items: center; display: inline-flex; gap: 11px; } .brand-mark { align-items: center; display: flex; height: 44px; justify-content: center; width: 38px; } .brand-mark img { filter: drop-shadow(0 4px 5px rgba(0,0,0,.15)); height: 100%; object-fit: contain; width: 100%; } .brand-copy { display: flex; flex-direction: column; line-height: .92; } .brand-copy strong { font-size: 14px; font-weight: 800; letter-spacing: -.04em; } .brand-copy small { font-family: 'DM Mono', monospace; font-size: 9px; letter-spacing: .38em; margin-left: 2px; margin-top: 4px; }
.main-nav { display: flex; gap: 34px; margin-left: 10vw; } .main-nav a { color: rgba(16,17,18,.64); font-size: 11px; font-weight: 700; transition: color .2s; } .main-nav a:hover, .text-link:hover, .back-top:hover { color: var(--gold); } .header-action { background: transparent; border: 1px solid var(--ink); border-radius: 100px; color: var(--ink); font-size: 10px; font-weight: 800; padding: 12px 17px; transition: background .2s, color .2s; } .header-action span { font-size: 14px; margin-left: 7px; } .header-action:hover { background: var(--ink); color: var(--cream); }
.hero { background: var(--cream); display: flex; min-height: 850px; overflow: hidden; padding: 170px 5vw 70px; position: relative; } .hero-content { max-width: 610px; position: relative; z-index: 2; } .eyebrow { align-items: center; color: var(--muted); display: flex; font-family: 'DM Mono', monospace; font-size: 10px; gap: 9px; letter-spacing: .12em; margin: 0 0 28px; text-transform: uppercase; } .live-dot { background: var(--gold); border-radius: 50%; box-shadow: 0 0 0 5px rgba(201,154,59,.12); height: 6px; width: 6px; } h1, h2, h3, p { margin-top: 0; } h1, h2 { font-size: clamp(58px, 7.6vw, 112px); letter-spacing: -.075em; line-height: .89; margin-bottom: 35px; } h1 em, h2 em { color: var(--gold); font-family: 'Playfair Display', Georgia, serif; font-weight: 600; letter-spacing: -.08em; } .hero-intro { color: rgba(16,17,18,.65); font-size: 14px; line-height: 1.75; max-width: 335px; } .hero-actions { align-items: center; display: flex; gap: 27px; margin-top: 35px; } .button { align-items: center; border: 0; border-radius: 100px; display: inline-flex; font-size: 11px; font-weight: 800; gap: 24px; justify-content: center; padding: 15px 19px; transition: transform .2s, background .2s; } .button:hover { transform: translateY(-2px); } .button-primary { background: var(--ink); color: var(--cream); } .button-primary:hover { background: var(--gold); } .button-dark { background: var(--ink); color: var(--cream); } .button span { font-size: 18px; font-weight: 400; line-height: .5; } .text-link { border-bottom: 1px solid rgba(16,17,18,.28); color: rgba(16,17,18,.7); font-size: 11px; font-weight: 700; padding-bottom: 4px; transition: color .2s; }
.hero-emblem { align-items: center; display: flex; height: 660px; justify-content: center; position: absolute; right: 1.5vw; top: 95px; width: min(52vw, 720px); } .hero-emblem img { filter: drop-shadow(0 28px 26px rgba(70,45,9,.3)); max-height: 520px; max-width: 75%; object-fit: contain; position: relative; transition: transform .1s linear; z-index: 1; } .orbit { border: 1px solid rgba(16,17,18,.13); border-radius: 50%; height: 600px; position: absolute; transform: rotate(-25deg) scaleX(.65); width: 600px; } .orbit-one { border-left-color: transparent; border-top-color: var(--gold); } .orbit-two { height: 510px; transform: rotate(48deg) scaleX(.8); width: 510px; } .emblem-caption { bottom: 42px; color: var(--muted); font-family: 'DM Mono', monospace; font-size: 9px; letter-spacing: .2em; position: absolute; right: 14%; transform: rotate(-90deg); } .emblem-caption span { background: var(--gold); border-radius: 50%; display: inline-block; height: 4px; margin: 0 8px; width: 4px; } .hero-ambient { border-radius: 50%; filter: blur(1px); opacity: .7; position: absolute; } .ambient-left { background: rgba(211,169,79,.13); height: 300px; left: -150px; top: 430px; width: 300px; } .ambient-right { background: rgba(226,190,107,.21); height: 260px; right: 21%; top: 240px; width: 260px; } .hero-bottom { align-items: center; bottom: 40px; color: var(--muted); display: flex; font-family: 'DM Mono', monospace; font-size: 9px; gap: 14px; left: 5vw; letter-spacing: .12em; position: absolute; text-transform: uppercase; } .scroll-line { background: var(--gold); display: block; height: 1px; width: 55px; }
.story-section { background: var(--ink); color: var(--cream); min-height: 2500px; position: relative; } .story-stage { align-items: center; display: flex; height: 100vh; min-height: 680px; overflow: hidden; padding: 10vw; position: sticky; top: 0; } .stage-copy { position: relative; width: 44%; z-index: 2; } .eyebrow.light, .story-slide .scene-kicker { color: rgba(243,239,229,.49); } .story-slide { opacity: 0; position: absolute; transform: translateY(22px); transition: opacity .45s ease, transform .45s ease; width: min(380px, 100%); } .story-slide.active { opacity: 1; position: relative; transform: translateY(0); } .scene-kicker { font-family: 'DM Mono', monospace; font-size: 10px; letter-spacing: .12em; margin-bottom: 26px; text-transform: uppercase; } .story-slide h2 { font-size: clamp(45px, 5vw, 75px); margin-bottom: 27px; } .story-slide h2 em { color: var(--gold-light); } .story-slide > p:last-child { color: rgba(243,239,229,.62); font-size: 14px; line-height: 1.8; max-width: 330px; } .story-graphic { height: 620px; position: absolute; right: 8%; width: 54%; } .graphic-sun { background: radial-gradient(circle, #e4b34e 0, rgba(201,154,59,.65) 22%, rgba(201,154,59,0) 69%); border-radius: 50%; height: 450px; position: absolute; right: 10%; top: 10%; width: 450px; } .graphic-pitch { border: 1px solid rgba(243,239,229,.25); height: 420px; position: absolute; right: 8%; top: 18%; transform: perspective(600px) rotateX(58deg) rotateZ(-27deg); width: 580px; } .pitch-circle { border: 1px solid rgba(243,239,229,.25); border-radius: 50%; height: 190px; left: 33%; position: absolute; top: 27%; width: 190px; } .pitch-line { background: rgba(243,239,229,.25); height: 100%; left: 50%; position: absolute; width: 1px; } .graphic-ball { color: var(--ink); font-size: 33px; position: absolute; right: 38%; top: 40%; z-index: 1; } .graphic-word { bottom: 12%; color: rgba(243,239,229,.4); font-size: clamp(30px, 4vw, 59px); font-weight: 800; letter-spacing: -.09em; position: absolute; right: 2%; transform: rotate(-90deg); } .story-progress { bottom: 12%; display: flex; gap: 8px; position: absolute; right: 10vw; } .story-progress span { background: rgba(243,239,229,.25); height: 3px; transition: background .3s, width .3s; width: 25px; } .story-progress span.active { background: var(--gold); width: 65px; }
.section-padding { padding: 150px 10vw; } .experience-section { background: var(--paper); } .section-heading { align-items: flex-end; display: flex; justify-content: space-between; margin-bottom: 80px; } .section-heading .eyebrow { align-self: flex-start; margin-top: 11px; } .section-heading h2 { font-size: clamp(58px, 7vw, 96px); margin: 0 auto 0 12%; } .section-lead { color: var(--muted); font-size: 13px; line-height: 1.8; margin: 0; max-width: 215px; } .discipline-grid { border-top: 1px solid var(--line); display: grid; grid-template-columns: repeat(3, 1fr); } .discipline-card { border-right: 1px solid var(--line); min-height: 360px; padding: 26px 33px 28px 0; } .discipline-card + .discipline-card { padding-left: 33px; } .discipline-card:last-child { border-right: 0; } .card-top { color: var(--muted); display: flex; font-family: 'DM Mono', monospace; font-size: 10px; justify-content: space-between; letter-spacing: .1em; text-transform: uppercase; } .card-tag { color: var(--gold); } .card-icon { color: var(--gold); height: 90px; margin: 39px 0 29px; width: 90px; } .card-icon svg { height: 100%; width: 100%; } .discipline-card h3 { font-size: 19px; letter-spacing: -.04em; margin-bottom: 13px; } .discipline-card p { color: var(--muted); font-size: 12px; line-height: 1.75; max-width: 245px; } .card-link { display: inline-block; font-size: 11px; font-weight: 800; margin-top: 21px; } .card-link span { color: var(--gold); font-size: 16px; margin-left: 8px; }
.club-section { background: var(--gold); display: grid; grid-template-columns: .95fr 1.05fr; padding-bottom: 120px; padding-top: 120px; } .club-image-panel { align-items: center; background: #191815; display: flex; min-height: 600px; overflow: hidden; position: relative; } .club-image-panel::after { background: repeating-linear-gradient(135deg, transparent, transparent 11px, rgba(231,192,106,.05) 12px, transparent 13px); content: ''; inset: 0; position: absolute; } .club-image-panel img { filter: drop-shadow(0 20px 15px rgba(0,0,0,.5)); margin: auto; max-height: 410px; max-width: 65%; object-fit: contain; position: relative; z-index: 1; } .image-panel-label { color: rgba(243,239,229,.65); display: flex; font-family: 'DM Mono', monospace; font-size: 9px; gap: 16px; left: 30px; letter-spacing: .13em; position: absolute; text-transform: uppercase; top: 29px; z-index: 2; } .image-panel-label span:first-child { color: var(--gold-light); } .image-panel-note { bottom: 28px; color: rgba(243,239,229,.62); font-size: 11px; left: 30px; line-height: 1.5; position: absolute; z-index: 2; } .image-panel-note em { color: var(--gold-light); font-family: 'Playfair Display', serif; } .club-copy-panel { padding: 61px 0 30px 10vw; } .club-copy-panel h2 { font-size: clamp(53px, 6vw, 84px); margin-bottom: 27px; } .club-description { color: rgba(16,17,18,.67); font-size: 14px; line-height: 1.8; max-width: 375px; } .fact-list { border-top: 1px solid rgba(16,17,18,.2); margin: 48px 0 39px; max-width: 410px; } .fact-list div { align-items: center; border-bottom: 1px solid rgba(16,17,18,.2); display: flex; font-family: 'DM Mono', monospace; font-size: 10px; justify-content: space-between; padding: 15px 0; } .fact-list span { color: rgba(16,17,18,.56); text-transform: uppercase; } .fact-list strong { font-weight: 500; } .fact-list .status { align-items: center; display: flex; gap: 7px; } .status i { background: #3f7b38; border-radius: 50%; display: inline-block; height: 6px; width: 6px; }
.visit-section { background: var(--ink); color: var(--cream); display: grid; gap: 10vw; grid-template-columns: 1fr 1fr; } .visit-intro h2 { font-size: clamp(60px, 7vw, 97px); } .visit-intro h2 em { color: var(--gold-light); } .visit-details { align-self: end; padding-bottom: 7px; } .detail-block { border-top: 1px solid rgba(243,239,229,.2); padding: 18px 0 20px; } .detail-label { color: var(--gold-light); display: block; font-family: 'DM Mono', monospace; font-size: 9px; letter-spacing: .12em; margin-bottom: 12px; text-transform: uppercase; } .detail-block p { color: rgba(243,239,229,.65); font-size: 13px; line-height: 1.75; } .visit-button { margin-top: 17px; } .site-footer { align-items: center; background: var(--ink); border-top: 1px solid rgba(243,239,229,.15); color: rgba(243,239,229,.53); display: flex; font-size: 10px; justify-content: space-between; padding: 27px 5vw; } .footer-brand { color: var(--cream); } .footer-brand .brand-mark { height: 32px; width: 28px; } .footer-brand .brand-copy strong { font-size: 11px; } .footer-brand .brand-copy small { font-size: 7px; } .site-footer p { margin: 0; } .back-top { transition: color .2s; }
.three-court { background: #17221d; border: 1px solid rgba(201,154,59,.3); height: min(49vw, 560px); margin-bottom: 82px; min-height: 360px; overflow: hidden; position: relative; } .three-court::before { background: radial-gradient(circle at 70% 28%, rgba(231,192,106,.2), transparent 23%), linear-gradient(135deg, rgba(243,239,229,.03), transparent 58%); content: ''; inset: 0; pointer-events: none; position: absolute; z-index: 1; } .three-court canvas { display: block; height: 100%; width: 100%; } .three-court-label { bottom: 22px; color: rgba(243,239,229,.72); display: flex; font-family: 'DM Mono', monospace; font-size: 9px; justify-content: space-between; left: 24px; letter-spacing: .12em; position: absolute; right: 24px; text-transform: uppercase; z-index: 2; } .three-court-label span:last-child { color: var(--gold-light); } .three-court-coordinate { color: rgba(243,239,229,.3); font-family: 'DM Mono', monospace; font-size: 8px; letter-spacing: .1em; position: absolute; right: 24px; text-transform: uppercase; top: 24px; z-index: 2; } .coordinate-two { bottom: 22px; left: 24px; right: auto; top: auto; transform: translateY(-17px); }
@media (max-width: 800px) { .site-header { height: 75px; padding: 0 6vw; } .main-nav { display: none; } .header-action { font-size: 9px; padding: 10px 12px; } .hero { min-height: 820px; padding: 135px 8vw 80px; } .hero-content { max-width: 70vw; } .hero-emblem { bottom: -48px; height: 390px; right: -80px; top: auto; width: 470px; } .hero-emblem img { max-height: 320px; } .orbit { height: 400px; width: 400px; } .orbit-two { height: 340px; width: 340px; } .hero-bottom { bottom: 22px; left: 8vw; } .story-section { min-height: 1850px; } .story-stage { align-items: flex-start; min-height: 600px; padding: 110px 8vw; } .stage-copy { width: 80%; } .story-graphic { bottom: 25px; height: 360px; right: -125px; width: 500px; } .graphic-sun { height: 300px; width: 300px; } .graphic-pitch { height: 250px; right: 10%; top: 18%; width: 360px; } .pitch-circle { height: 110px; width: 110px; } .graphic-word { bottom: 16%; font-size: 30px; } .story-progress { bottom: 40px; left: 8vw; right: auto; } .section-padding { padding: 95px 8vw; } .section-heading { align-items: flex-start; display: block; margin-bottom: 53px; } .section-heading h2 { margin: 0 0 25px; } .section-lead { max-width: 290px; } .three-court { height: 430px; margin-bottom: 53px; min-height: 0; } .three-court-label { bottom: 15px; flex-direction: column; gap: 6px; left: 15px; right: auto; } .three-court-coordinate { right: 15px; top: 15px; } .coordinate-two { bottom: 15px; left: auto; right: 15px; top: auto; transform: none; } .discipline-grid { display: block; } .discipline-card, .discipline-card + .discipline-card { border-bottom: 1px solid var(--line); border-right: 0; min-height: auto; padding: 24px 0 33px; } .discipline-card:last-child { border-bottom: 0; } .card-icon { margin-top: 27px; } .club-section { display: block; padding: 0 8vw 95px; } .club-image-panel { min-height: 430px; margin: 0 -8vw; } .club-image-panel img { max-height: 300px; } .club-copy-panel { padding: 83px 0 0; } .visit-section { display: block; } .visit-details { margin-top: 55px; } .site-footer { align-items: flex-start; flex-wrap: wrap; gap: 20px; } .site-footer p { order: 3; width: 100%; } }
@media (prefers-reduced-motion: reduce) { html { scroll-behavior: auto; } *, *::before, *::after { scroll-behavior: auto !important; transition-duration: .01ms !important; } }
.story-graphic .three-court { background: transparent; border: 0; cursor: crosshair; height: 100%; margin: 0; min-height: 0; width: 100%; }
.story-graphic .three-court::before { background: radial-gradient(circle at 58% 38%, rgba(231,192,106,.18), transparent 24%), linear-gradient(135deg, rgba(243,239,229,.04), transparent 58%); }
</style>
